apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sdo
data:
  PORT: "3000"
  NODE_ENV: "production"

  ATLAS_URI: "mongodb://appadmin:appadminpass@mongo:27017/mernapp?authSource=admin"
  MONGO_URI: "mongodb://appadmin:appadminpass@mongo:27017/mernapp?authSource=admin"
  MONGODB_URI: "mongodb://appadmin:appadminpass@mongo:27017/mernapp?authSource=admin"
  MONGODB_URL: "mongodb://appadmin:appadminpass@mongo:27017/mernapp?authSource=admin"

  MONGO_DB_NAME: "mernapp"

