apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: sdo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/server
        command: ["npm","start"]
        ports:
          - containerPort: 3000
        envFrom:
          - secretRef:
              name: mongo-secret
          - configMapRef:
              name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: sdo
spec:
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
