apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sdo
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }

    http {
      sendfile on;

      upstream web-app { server app:3000; }

      server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/ssl/certs/localhost.crt;
        ssl_certificate_key /etc/ssl/private/localhost.key;

        # Serve React app
        root /usr/share/nginx/html;
        index index.html;

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|woff|woff2|eot|ttf|svg|map)$ {
          try_files $uri $uri/ =404;
        }

        location /api/ {
          proxy_pass            http://web-app/;
          proxy_http_version    1.1;
          proxy_set_header      Upgrade $http_upgrade;
          proxy_set_header      Connection keep-alive;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header      X-Forwarded-Proto $scheme;
        }

        # SPA fallback
        location / {
          try_files $uri /index.html;
        }
      }
    }
